[package]
name = "discrete_log"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
num-bigint = "0.4.4"
ark-ff = "0.4.2"
ark-ec = "0.4.2"
ark-std = "0.4.0"